sudo: false
language: cpp

install:
 - export OS=${TRAVIS_OS_NAME}
 - export BASE=`pwd`
 - export BOOST_URL=https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.gz
 - mkdir ${BASE}/usr
 - if [ "$CXX" == "g++" ]; then export CXX="g++-6" CC="gcc-6"; fi
 - if [ "$CXX" == "clang++" ] && [ "$OS" == "linux" ]; then \
   export CXX="clang++-3.7" CC="clang-3.7" ; fi
 - if [ "$OS" == "mac"]; then curl -L $BOOST_URL | tar xz \
   && ./Configure darwin64-x86_64-cc --prefix=${BASE}/usr \
   && make -j `nproc` && make install > /dev/null && cd ..; fi

matrix:
  include:
    - os: osx
      compiler: clang
      env: FLAGS="-DMQTT_NO_TLS=ON  -DMQTT_USE_WS=ON"
    - os: osx
      compiler: clang
      env: FLAGS="-DMQTT_NO_TLS=ON  -DMQTT_USE_WS=OFF"
    - os: osx
      compiler: clang
      env: FLAGS="-DMQTT_NO_TLS=OFF -DMQTT_USE_WS=ON"
    - os: osx
      compiler: clang
      env: FLAGS="-DMQTT_NO_TLS=OFF -DMQTT_USE_WS=OFF"
    - os: linux
      compiler: clang
      env: FLAGS="-DMQTT_NO_TLS=ON  -DMQTT_USE_WS=ON"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise
          packages:
            - libboost-all-dev
            - bzip2
            - libssl-dev
            - cmake
            - clang-3.7
            - libc6-dbg
    - os: linux
      compiler: clang
      env: FLAGS="-DMQTT_NO_TLS=ON  -DMQTT_USE_WS=OFF"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise
          packages:
            - bzip2
            - libboost-all-dev
            - clang-3.7
            - cmake
            - libc6-dbg
            - libssl-dev
    - os: linux
      compiler: gcc
      env: FLAGS="-DMQTT_NO_TLS=OFF -DMQTT_USE_WS=ON"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - gcc-6
            - cmake
            - libboost-all-dev
            - bzip2
            - libc6-dbg
    - os: linux
      compiler: gcc
      env: FLAGS="-DMQTT_NO_TLS=OFF -DMQTT_USE_WS=OFF"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - cmake
            - libboost-all-dev
            - bzip2
            - libc6-dbg

script:
  - mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER="${CXX}" -DCMAKE_C_COMPILER="${CC}" -DCMAKE_LIBRARY_PATH="${BASE}/usr/lib" -DBOOST_ROOT="${BASE}/usr" -DOPENSSL_ROOT_DIR="${BASE}/usr" $FLAGS .. && make VERBOSE=1 && ctest -VV
